# safelist
branches:
  only:
  - master
language: c
os: linux
arch: amd64
script: ./configure --with-restconf=evhtp && make && sudo make install
before_script:
  - sudo apt-get install -y libevent libevent-dev cmake
  - ./test/travis/before_script.sh
  - ./test/travis/build_evhtp.sh
