# safelist
branches:
  only:
  - master
language: c
os: linux
arch: amd64
before_script:
  - sudo apt-get install -y libfcgi-dev
  - ./test/travis/before_script.sh
script:
  - ./configure --with-restconf=evhtp && make && sudo make install
