language: c
os: linux
# safelist
branches:
  only:
  - master
jobs:
- arch: amd64
- dist: bionic
- before_script:
  - sudo apt-get install -y libfcgi-dev
  - ./test/travis/before_script.sh
- script: ./configure --with-restconf=fcgi && make && sudo make install
jobs:
- arch: amd64
- dist: xenial
- script: ./configure --with-restconf=evhtp && make && sudo make install
 